name: example
description: A new Flutter project.
version: 2.6.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  accordion:
    path: ..
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
